#!/bin/bash
# mock-engine.sh - A deterministic mock that impersonates qodercli (and the
# other CLI agents symlinked to it: claude, codex, qwen — they all pass the
# instruction via -p, and any extra flags like --yolo / -m <model> are skipped
# harmlessly by the arg loop below).
#
# The QoderCLIAgent invokes: qodercli -p "<prompt>" 2>&1
# This script:
#   1. Reads the -p flag value as the prompt.
#   2. Returns a canned response based on prompt keywords.
#   3. Exits with code 0 (success) by default; use MOCK_EXIT_CODE to override.
#
# Environment variables for controlling behavior:
#   MOCK_EXIT_CODE   - override the exit code (default: 0)
#   MOCK_RESPONSE    - override the entire response text
#   MOCK_FAIL        - if set to "1", exit with code 1 and an error message
#   MOCK_TIMEOUT     - if set, sleep for that many seconds (to simulate timeout)
#   MOCK_CREATE_FILE - if set, create this file in the current working directory
#   MOCK_FAIL_COUNT  - fail the first N invocations, then succeed (requires MOCK_STATE_FILE)
#   MOCK_STATE_FILE  - path to a temp file used as invocation counter for MOCK_FAIL_COUNT
#
# Judge prompt auto-detection:
#   When the prompt contains "Required Response Format" AND "## Criteria",
#   the script treats it as an agent_judge evaluation prompt and returns
#   a valid JSON response with all criteria marked as passed. This allows
#   --auto mode (which uses agent_judge) to work in mock scenarios.

set -euo pipefail

PROMPT=""

# Parse arguments - qodercli/claude pass: -p "<prompt>". Any other flags
# (e.g. qwen's --yolo / -m <model>) are skipped harmlessly.
while [[ $# -gt 0 ]]; do
  case "$1" in
    -p)
      shift
      PROMPT="$1"
      ;;
  esac
  shift
done

# qwen passes the prompt on stdin (not -p, which it deprecated). When no -p was
# given and stdin is a pipe, read the prompt from there so the mock impersonates
# qwen faithfully. The -z guard means -p callers are unaffected.
if [[ -z "$PROMPT" && ! -t 0 ]]; then
  PROMPT="$(cat)"
fi

# Handle timeout simulation
if [[ -n "${MOCK_TIMEOUT:-}" ]]; then
  sleep "$MOCK_TIMEOUT"
fi

# Handle forced failure
if [[ "${MOCK_FAIL:-}" == "1" ]]; then
  echo "Error: mock engine forced failure" >&2
  exit "${MOCK_EXIT_CODE:-1}"
fi

# Handle fail-then-succeed pattern via MOCK_FAIL_COUNT.
# Uses a state file (MOCK_STATE_FILE) to track invocation count.
# The first MOCK_FAIL_COUNT invocations fail; subsequent ones succeed.
if [[ -n "${MOCK_FAIL_COUNT:-}" && -n "${MOCK_STATE_FILE:-}" ]]; then
  CALL_NUM=1
  if [[ -f "$MOCK_STATE_FILE" ]]; then
    CALL_NUM=$(( $(cat "$MOCK_STATE_FILE") + 1 ))
  fi
  echo "$CALL_NUM" > "$MOCK_STATE_FILE"
  if (( CALL_NUM <= MOCK_FAIL_COUNT )); then
    echo "Error: mock engine transient failure (attempt $CALL_NUM/$MOCK_FAIL_COUNT)" >&2
    exit "${MOCK_EXIT_CODE:-1}"
  fi
fi

# Handle file creation (for files_exist tests)
if [[ -n "${MOCK_CREATE_FILE:-}" ]]; then
  mkdir -p "$(dirname "$MOCK_CREATE_FILE")"
  echo "Generated by mock engine" > "$MOCK_CREATE_FILE"
fi

# Handle agent_judge evaluation prompts.
# The judge prompt always contains "Required Response Format" and "## Criteria".
# We parse the numbered criteria and return a valid JSON response so that
# agent_judge can succeed in mock/CI scenarios without a real LLM.
if echo "$PROMPT" | grep -q "Required Response Format" && echo "$PROMPT" | grep -q "## Criteria"; then
  # Build JSON using python3 for correct escaping of all special characters
  # (quotes, backslashes, control chars, Unicode, etc.).
  JSON_RESULTS=$(echo "$PROMPT" | grep -E '^[[:space:]]*[0-9]+\.' | python3 -c '
import json, sys
items = []
for line in sys.stdin:
    text = line.strip()
    # Strip leading "N. " prefix
    dot = text.find(".")
    if dot != -1:
        text = text[dot+1:].strip()
    items.append({"criterion": text, "passed": True, "evidence": "Mock engine: criterion satisfied based on agent output analysis"})
print(json.dumps({"results": items}))
')
  echo "$JSON_RESULTS"
  exit "${MOCK_EXIT_CODE:-0}"
fi

# Handle custom response override
if [[ -n "${MOCK_RESPONSE:-}" ]]; then
  echo "$MOCK_RESPONSE"
  exit "${MOCK_EXIT_CODE:-0}"
fi

# Default: return deterministic response based on prompt keywords
if echo "$PROMPT" | grep -qi "null"; then
  echo "I found a null pointer bug at line 42. The variable 'data' is dereferenced without a null check, which could cause a NullPointerException at runtime."
elif echo "$PROMPT" | grep -qi "review"; then
  echo "Code review complete. Found 2 issues: 1) Missing error handling in processData(). 2) Potential race condition in updateCounter(). Recommendation: Add proper error handling and use mutex for thread safety."
elif echo "$PROMPT" | grep -qi "hello"; then
  echo "Hello! I'm ready to assist you with code review and analysis."
elif echo "$PROMPT" | grep -qi "bug"; then
  echo "Bug analysis complete. Found a boundary check issue: the loop iterates from 0 to array.length (inclusive), causing an off-by-one error that leads to ArrayIndexOutOfBoundsException."
elif echo "$PROMPT" | grep -qi "error"; then
  echo "Error analysis: The function fails to handle the edge case where input is empty. Adding a guard clause at the top of the function would prevent the downstream TypeError."
elif echo "$PROMPT" | grep -qi "fail"; then
  echo "Analysis indicates LGTM - no issues found." 
else
  echo "I have analyzed the provided code. The implementation looks correct with no obvious issues detected. Output includes the prompt content for verification: $PROMPT"
fi

exit "${MOCK_EXIT_CODE:-0}"
