version: 2

project_name: skill-up

before:
  hooks:
    - go mod tidy

builds:
  - id: skill-up
    main: ./cmd/skill-up
    binary: skill-up
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - skill-up
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^style"
      - "^docs"
      - Merge pull request
      - Merge branch
